#Requires -Version 5.1
param(
    [Parameter(Mandatory = $false)]
    [string]$MigrationName,

    [Parameter(Mandatory = $false)]
    [ValidateSet('ConsilientDbContext', 'UsersDbContext')]
    [string]$Context
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Available contexts
$AvailableContexts = @('ConsilientDbContext', 'UsersDbContext')

# Interactive context selection if not provided
if ([string]::IsNullOrWhiteSpace($Context)) {
    Write-Host 'Select DbContext:' -ForegroundColor Cyan
    for ($i = 0; $i -lt $AvailableContexts.Count; $i++) {
        Write-Host "  [$($i + 1)] $($AvailableContexts[$i])"
    }
    do {
        $Selection = Read-Host 'Enter selection (1-2)'
        $SelectionNum = $Selection -as [int]
    } while ($SelectionNum -lt 1 -or $SelectionNum -gt $AvailableContexts.Count)
    $Context = $AvailableContexts[$SelectionNum - 1]
}

# Interactive loop to get migration name if not provided as parameter
if ([string]::IsNullOrWhiteSpace($MigrationName)) {
    do {
        $MigrationName = Read-Host 'Enter migration name (or press Ctrl+C to exit)'
    } while (-not $MigrationName)
}

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\')).Path
$SrcRoot = Join-Path $RepoRoot 'src'
$MigrationsProject = Join-Path $SrcRoot 'Consilient.Data.Migrations'

# Convention-based derivation
if ($Context -match '^(.*)DbContext$') {
    $ContextShort = $Matches[1]
} else {
    $ContextShort = $Context
}

$Namespace = "Consilient.Data.Migrations.$ContextShort"
$OutputDir = $ContextShort
$FullOutputDir = Join-Path $MigrationsProject $OutputDir
$SnapshotFile = Join-Path $FullOutputDir "${Context}ModelSnapshot.cs"

Write-Host "Adding migration '$MigrationName' for $Context..." -ForegroundColor Cyan

# Ensure output directory exists
if (-not (Test-Path $FullOutputDir)) {
    New-Item -ItemType Directory -Path $FullOutputDir | Out-Null
}

# Ensure snapshot file exists so EF Core places it in the correct location
# This prevents EF from creating nested folders based on namespace
if (-not (Test-Path $SnapshotFile)) {
    Write-Host 'Creating placeholder snapshot file to ensure correct output location...'
    $SnapshotContent = @"
// <auto-generated />
using Consilient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace $Namespace
{
    [DbContext(typeof($Context))]
    partial class ${Context}ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
        }
    }
}
"@
    Set-Content -Path $SnapshotFile -Value $SnapshotContent -Encoding UTF8
}

# Run from src directory where local tools are configured
Push-Location $SrcRoot
try {
    dotnet ef migrations add $MigrationName `
        --context $Context `
        --project $MigrationsProject `
        --startup-project $MigrationsProject `
        --output-dir $OutputDir `
        --namespace $Namespace `
        --verbose

    if ($LASTEXITCODE -ne 0) {
        Write-Host "Migration add failed for $Context" -ForegroundColor Red
        exit 1
    }
}
finally {
    Pop-Location
}

Write-Host 'Migration added successfully.' -ForegroundColor Green
