// <auto-generated />
using System;
using Consilient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consilient.Data.Migrations.Consilient
{
    [DbContext(typeof(ConsilientDbContext))]
    [Migration("20260127164213_RemoveExclusionReason")]
    partial class RemoveExclusionReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consilient.Data.Entities.Billing.BillingCode", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_BillingCodes");

                    b.HasAlternateKey("Code")
                        .HasName("AK_BillingCodes_Code");

                    b.ToTable("BillingCodes", "Billing");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Billing.VisitServiceBilling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_VisitServiceBilling");

                    b.HasAlternateKey("VisitId", "ServiceTypeId", "BillingCodeId")
                        .HasName("AK_VisitServiceBillings_VisitId_ServiceTypeId_BillingCodeId");

                    b.HasIndex("BillingCodeId")
                        .HasDatabaseName("IX_VisitServiceBillings_BillingCodeId");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("IX_VisitServiceBillings_ServiceTypeId");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("IX_VisitServiceBillings_VisitId");

                    b.ToTable("VisitServiceBillings", "Billing");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.ToTable("Facilities", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Hospitalization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalizationStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("PsychEvaluation")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_Hospitalization");

                    b.HasAlternateKey("CaseId")
                        .HasName("AK_Hospitalizations_CaseId");

                    b.HasAlternateKey("CaseId", "PatientId")
                        .HasName("AK_Hospitalizations_CaseId_PatientId");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("IX_Hospitalizations_FacilityId");

                    b.HasIndex("HospitalizationStatusId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Hospitalizations_PatientId");

                    b.ToTable("Hospitalizations", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.HospitalizationInsurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("HospitalizationId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_HospitalizationInsurance");

                    b.HasIndex("HospitalizationId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("HospitalizationInsurances", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.HospitalizationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_HospitalizationStatus");

                    b.ToTable("HospitalizationStatuses", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.HospitalizationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("HospitalizationId")
                        .HasColumnType("int");

                    b.Property<int>("NewStatusId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_HospitalizationStatusHistory");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("IX_HospitalizationStatusHistories_ChangedAt");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("IX_HospitalizationStatusHistories_ChangedByUserId");

                    b.HasIndex("HospitalizationId")
                        .HasDatabaseName("IX_HospitalizationStatusHistories_HospitalizationId");

                    b.HasIndex("NewStatusId")
                        .HasDatabaseName("IX_HospitalizationStatusHistories_NewStatusId");

                    b.ToTable("HospitalizationStatusHistories", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.ToTable("Patients", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.PatientFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MRN");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_PatientFacility");

                    b.HasIndex("PatientId");

                    b.HasIndex("FacilityId", "Mrn")
                        .IsUnique()
                        .HasDatabaseName("IX_PatientFacilities_FacilityId_MRN");

                    b.ToTable("PatientFacilities", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<string>("TitleExtension")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_Provider");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Providers_EmployeeId")
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.ToTable("Providers", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bed")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("DateServiced")
                        .HasColumnType("date");

                    b.Property<int>("HospitalizationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsScribeServiceOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_Visit");

                    b.HasIndex("HospitalizationId");

                    b.HasIndex(new[] { "DateServiced" }, "IX_Visits_DateServiced");

                    b.ToTable("Visits", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.VisitAttendant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_VisitAttendant");

                    b.HasAlternateKey("VisitId", "ProviderId")
                        .HasName("AK_VisitAttendants_VisitId_ProviderId");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("IX_VisitAttendants_ProviderId");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("IX_VisitAttendants_VisitId");

                    b.ToTable("VisitAttendants", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.VisitEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnteredByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventOccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_VisitEvent");

                    b.HasIndex("EnteredByUserId")
                        .HasDatabaseName("IX_VisitEvents_EnteredByUserId");

                    b.HasIndex("EventOccurredAt")
                        .HasDatabaseName("IX_VisitEvents_EventOccurredAt");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("IX_VisitEvents_EventTypeId");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("IX_VisitEvents_VisitId");

                    b.ToTable("VisitEvents", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.VisitEventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_VisitEventType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_VisitEventTypes_Code");

                    b.ToTable("VisitEventTypes", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Compensation.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<string>("TitleExtension")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.ToTable("Employees", "Compensation");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Compensation.ProviderContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_ProviderContract");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FacilityId");

                    b.ToTable("ProviderContracts", "Compensation");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsContracted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("PhysicianIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.ToTable("Insurances", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Staging.ProviderAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Admit")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AttendingMD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bed")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("H_P")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HospitalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HospitalizationWasCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Imported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Insurance")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IsCleared")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedNursePractitionerLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedPatientFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedPatientLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedPhysicianLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NursePractitioner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("NursePractitionerWasCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PatientFacilityWasCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PatientWasCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PhysicianWasCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PsychEval")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ResolvedHospitalizationId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedHospitalizationStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedNursePractitionerId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedPatientId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedPhysicianId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedVisitId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<bool>("ShouldImport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ValidationErrorsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValidationErrors");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ResolvedHospitalizationId");

                    b.HasIndex("ResolvedHospitalizationStatusId");

                    b.HasIndex("ResolvedNursePractitionerId");

                    b.HasIndex("ResolvedPatientId");

                    b.HasIndex("ResolvedPhysicianId");

                    b.HasIndex("ResolvedVisitId");

                    b.ToTable("ProviderAssignments", "staging");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Staging.ProviderAssignmentBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_ProviderAssignmentBatches");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_ProviderAssignmentBatches_CreatedByUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ProviderAssignmentBatches_Status");

                    b.HasIndex("FacilityId", "Date")
                        .HasDatabaseName("IX_ProviderAssignmentBatches_FacilityId_Date");

                    b.ToTable("ProviderAssignmentBatches", "staging");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Billing.VisitServiceBilling", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Billing.BillingCode", "BillingCode")
                        .WithMany()
                        .HasForeignKey("BillingCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VisitServiceBillings_BillingCodes_BillingCodeId");

                    b.HasOne("Consilient.Data.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VisitServiceBillings_ServiceTypes_ServiceTypeId");

                    b.HasOne("Consilient.Data.Entities.Clinical.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VisitServiceBillings_Visits_VisitId");

                    b.Navigation("BillingCode");

                    b.Navigation("ServiceType");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Hospitalization", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Clinical.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Hospitalizations_Facilities_FacilityId");

                    b.HasOne("Consilient.Data.Entities.Clinical.HospitalizationStatus", "HospitalizationStatus")
                        .WithMany()
                        .HasForeignKey("HospitalizationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Consilient.Data.Entities.Clinical.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Hospitalizations_Patients_PatientId");

                    b.Navigation("Facility");

                    b.Navigation("HospitalizationStatus");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.HospitalizationInsurance", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Clinical.Hospitalization", "Hospitalization")
                        .WithMany()
                        .HasForeignKey("HospitalizationId")
                        .IsRequired()
                        .HasConstraintName("FK_HospitalizationInsurances_Hospitalizations");

                    b.HasOne("Consilient.Data.Entities.Insurance", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .IsRequired()
                        .HasConstraintName("FK_HospitalizationInsurances_Insurances");

                    b.Navigation("Hospitalization");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.HospitalizationStatusHistory", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Clinical.Hospitalization", null)
                        .WithMany()
                        .HasForeignKey("HospitalizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HospitalizationStatusHistories_Hospitalizations_HospitalizationId");

                    b.HasOne("Consilient.Data.Entities.Clinical.HospitalizationStatus", null)
                        .WithMany()
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HospitalizationStatusHistories_HospitalizationStatuses_NewStatusId");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.PatientFacility", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Clinical.Facility", "Facility")
                        .WithMany("PatientFacilities")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientFacilities_Facilities");

                    b.HasOne("Consilient.Data.Entities.Clinical.Patient", "Patient")
                        .WithMany("PatientFacilities")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientFacilities_Patients");

                    b.Navigation("Facility");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Provider", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Compensation.Employee", null)
                        .WithOne()
                        .HasForeignKey("Consilient.Data.Entities.Clinical.Provider", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Providers_Employees_EmployeeId");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Visit", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Clinical.Hospitalization", "Hospitalization")
                        .WithMany()
                        .HasForeignKey("HospitalizationId")
                        .IsRequired()
                        .HasConstraintName("FK_Visits_Hospitalizations_HospitalizationId");

                    b.Navigation("Hospitalization");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.VisitAttendant", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Clinical.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VisitAttendants_Providers_ProviderId");

                    b.HasOne("Consilient.Data.Entities.Clinical.Visit", "Visit")
                        .WithMany("VisitAttendants")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VisitAttendants_Visits_VisitId");

                    b.Navigation("Provider");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.VisitEvent", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Clinical.VisitEventType", null)
                        .WithMany("VisitEvents")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VisitEvents_VisitEventTypes_EventTypeId");

                    b.HasOne("Consilient.Data.Entities.Clinical.Visit", null)
                        .WithMany("VisitEvents")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VisitEvents_Visits_VisitId");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Compensation.ProviderContract", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Compensation.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_ProviderContracts_Employee");

                    b.HasOne("Consilient.Data.Entities.Clinical.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_ProviderContracts_Facility");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Staging.ProviderAssignment", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Staging.ProviderAssignmentBatch", null)
                        .WithMany("ProviderAssignments")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consilient.Data.Entities.Clinical.Hospitalization", "ResolvedHospitalization")
                        .WithMany()
                        .HasForeignKey("ResolvedHospitalizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Consilient.Data.Entities.Clinical.HospitalizationStatus", "ResolvedHospitalizationStatus")
                        .WithMany()
                        .HasForeignKey("ResolvedHospitalizationStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Consilient.Data.Entities.Clinical.Provider", "ResolvedNursePractitioner")
                        .WithMany()
                        .HasForeignKey("ResolvedNursePractitionerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Consilient.Data.Entities.Clinical.Patient", "ResolvedPatient")
                        .WithMany()
                        .HasForeignKey("ResolvedPatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Consilient.Data.Entities.Clinical.Provider", "ResolvedPhysician")
                        .WithMany()
                        .HasForeignKey("ResolvedPhysicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Consilient.Data.Entities.Clinical.Visit", "ResolvedVisit")
                        .WithMany()
                        .HasForeignKey("ResolvedVisitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ResolvedHospitalization");

                    b.Navigation("ResolvedHospitalizationStatus");

                    b.Navigation("ResolvedNursePractitioner");

                    b.Navigation("ResolvedPatient");

                    b.Navigation("ResolvedPhysician");

                    b.Navigation("ResolvedVisit");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Facility", b =>
                {
                    b.Navigation("PatientFacilities");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Patient", b =>
                {
                    b.Navigation("PatientFacilities");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.Visit", b =>
                {
                    b.Navigation("VisitAttendants");

                    b.Navigation("VisitEvents");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Clinical.VisitEventType", b =>
                {
                    b.Navigation("VisitEvents");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Staging.ProviderAssignmentBatch", b =>
                {
                    b.Navigation("ProviderAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
