name: Initialize Workflow Configuration
description: Initializes workflow configuration by validating environment inputs

inputs:
  environment:
    description: 'Target environment (dev/prod/etc)'
    required: false
    default: ''

outputs:
  environment:
    description: 'Computed deployment environment'
    value: ${{ steps.setenv.outputs.environment }}

runs:
  using: composite
  steps:
    - name: Validate environment input
      uses: ./.github/actions/validate-inputs
      with:
        environment: ${{ inputs.environment || 'dev' }}

    - name: Set environment output
      id: setenv
      shell: bash
      run: |
        ENVIRONMENT_INPUT="${{ inputs.environment }}"

        # Default to dev if no input
        if [ -z "$ENVIRONMENT_INPUT" ]; then
          ENVIRONMENT_INPUT="dev"
        fi

        echo "environment=$ENVIRONMENT_INPUT" >> $GITHUB_OUTPUT

    - name: Summary
      shell: bash
      run: |
        echo "### Workflow Initialization Complete ✅" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** \`${{ steps.setenv.outputs.environment }}\`" >> $GITHUB_STEP_SUMMARY
