name: Create GitHub Step Summary
description: Creates a standardized GitHub Actions step summary with consistent formatting and emojis

inputs:
  title:
    description: 'Summary title'
    required: true
  status:
    description: 'Deployment status (success, failure, warning, skipped)'
    required: true
  sections:
    description: 'JSON object with section titles and content arrays'
    required: false
    default: '{}'
  details:
    description: 'Additional details to append'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Generate Summary
      shell: bash
      run: |
        set -e

        TITLE='${{ inputs.title }}'
        STATUS='${{ inputs.status }}'
        SECTIONS='${{ inputs.sections }}'
        DETAILS='${{ inputs.details }}'

        # Emoji mapping for status
        case "$STATUS" in
          success)
            EMOJI="✅"
            COLOR="brightgreen"
            ;;
          failure)
            EMOJI="❌"
            COLOR="red"
            ;;
          warning)
            EMOJI="⚠️"
            COLOR="orange"
            ;;
          skipped)
            EMOJI="⏭️"
            COLOR="lightgrey"
            ;;
          *)
            EMOJI="ℹ️"
            COLOR="blue"
            ;;
        esac

        # Write header
        echo "### $EMOJI $TITLE" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        # Parse and write sections
        if [ "$SECTIONS" != "{}" ] && [ -n "$SECTIONS" ]; then
          echo "$SECTIONS" | jq -r 'to_entries | .[] | .key' | while read -r section_key; do
            SECTION_TITLE=$(echo "$SECTIONS" | jq -r ".\"$section_key\".title // \"$section_key\"")
            SECTION_CONTENT=$(echo "$SECTIONS" | jq -r ".\"$section_key\".content // []")

            if [ "$SECTION_TITLE" != "null" ]; then
              echo "**$SECTION_TITLE:**" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY

              if echo "$SECTION_CONTENT" | jq -e 'type == "array"' >/dev/null 2>&1; then
                echo "$SECTION_CONTENT" | jq -r '.[] // empty' | while read -r item; do
                  if [ -n "$item" ]; then
                    echo "- $item" >> $GITHUB_STEP_SUMMARY
                  fi
                done
              else
                echo "$SECTION_CONTENT" >> $GITHUB_STEP_SUMMARY
              fi

              echo "" >> $GITHUB_STEP_SUMMARY
            fi
          done
        fi

        # Append additional details if provided
        if [ -n "$DETAILS" ]; then
          echo "$DETAILS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi

        # Footer with timestamp
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "_Generated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')_" >> $GITHUB_STEP_SUMMARY
