name: 'Discover Databases'
description: 'Scan directory for database directories'

inputs:
  scripts_path:
    description: 'Root path to database scripts'
    required: true
    default: 'src/Databases'

outputs:
  databases:
    description: 'JSON array of discovered databases with all metadata'
    value: ${{ steps.discover.outputs.databases }}
  database_directories:
    description: 'JSON array of database directory names'
    value: ${{ steps.discover.outputs.database_directories }}
  database_configs:
    description: 'JSON object mapping database names to config data'
    value: ${{ steps.discover.outputs.database_configs }}
  count:
    description: 'Number of databases discovered'
    value: ${{ steps.discover.outputs.count }}

runs:
  using: 'composite'
  steps:
    - name: Discover databases
      id: discover
      shell: bash
      run: ${{ github.action_path }}/discover-databases.sh
      env:
        SCRIPTS_PATH: ${{ inputs.scripts_path }}

    - name: Summary
      shell: bash
      run: |
        echo "### Database Discovery Complete ðŸ”" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Databases Found:** ${{ steps.discover.outputs.count }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ "${{ steps.discover.outputs.count }}" -gt "0" ]; then
          echo "**Discovered Databases:**" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.discover.outputs.database_directories }}' | jq -r '.[]' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        else
          echo "_No databases found in \`${{ inputs.scripts_path }}\`_" >> $GITHUB_STEP_SUMMARY
        fi
