//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

namespace Consilient.Api {

export interface AuthenticateUserRequest {
    userName: string;
    password: string;
}

export interface ClaimDto {
    type: string;
    value: string;
}

export interface Consilient_Api_Controllers_AuthenticateUserApiResponse {
    succeeded: boolean;
    errors?: string[] | null;
    userClaims?: ClaimDto[] | null;
}

export interface Consilient_Data_GraphQL_GraphQlError {
    message: string;
}

export interface Consilient_Data_GraphQL_QueryRequest {
    query?: string | null;
}

export interface Consilient_Data_GraphQL_QueryResult {
    errors?: Consilient_Data_GraphQL_GraphQlError[] | null;
    data?: { [key: string]: any; } | null;
    extensions?: { [key: string]: any; } | null;
}

export interface CreateEmployeeRequest {
    firstName?: string | null;
    lastName?: string | null;
    titleExtension?: string | null;
    isProvider: boolean;
    role?: string | null;
    isAdministrator: boolean;
    email?: string | null;
    canApproveVisits: boolean;
}

export interface CreateFacilityRequest {
    facilityName?: string | null;
    facilityAbbreviation?: string | null;
}

export interface CreateInsuranceRequest {
    insuranceCode?: string | null;
    insuranceDescription?: string | null;
    physicianIncluded?: boolean | null;
    isContracted?: boolean | null;
    codeAndDescription: string;
}

export interface CreatePatientRequest {
    firstName: string;
    lastName: string;
    patientBirthDate?: string | null;
    facilityId?: number | null;
    mrn?: string | null;
}

export interface CreateServiceTypeRequest {
    description?: string | null;
    cptCode?: number | null;
}

export interface CreateVisitRequest {
    dateServiced: string;
    hospitalizationId: number;
    serviceTypeId: number;
    isScribeServiceOnly: boolean;
}

export interface EmployeeDto {
    id: number;
    firstName?: string | null;
    lastName?: string | null;
    titleExtension?: string | null;
    isProvider: boolean;
    role?: string | null;
    isAdministrator: boolean;
    email?: string | null;
    canApproveVisits: boolean;
}

export interface EmployeeVisitCountDto {
    providerId: number;
    providerLastName: string;
    providerFirstName: string;
    providerType: number;
    facilityId: number;
    facilityAbbreviation: string;
    patientId: number;
    patientMRN: string;
    patientLastName: string;
    patientFirstName: string;
    visitId: number;
    dateServiced: string;
    room: string;
    bed: string;
}

export interface ExternalAuthenticateRequest {
    provider: string;
    code: string;
    codeVerifier: string;
    redirectUri: string;
}

export interface FacilityDto {
    id: number;
    name?: string | null;
    abbreviation?: string | null;
}

export interface FileUploadResult {
    fileName: string;
    serviceDate: string;
    facilityId: number;
    message: string;
    batchId: string;
}

export enum Gender {
    _1 = 1,
    _2 = 2,
    _3 = 3,
}

export interface HospitalizationDto {
    id: number;
    patientId: number;
    caseId: number;
    facilityId: number;
    psychEvaluation: boolean;
    admissionDate: string;
    dischargeDate?: string | null;
    hospitalizationStatusId: number;
}

export interface HospitalizationStatusDto {
    id: number;
    code: string;
    name: string;
    billingCode: string;
    color: string;
    displayOrder: number;
    type: HospitalizationStatusType;
    iconName?: string | null;
}

export enum HospitalizationStatusType {
    _0 = 0,
    _1 = 1,
}

export interface InsertVisitEventRequest {
    visitId: number;
    eventTypeId: number;
    eventOccurredAt: string;
    description: string;
}

export interface InsuranceDto {
    id: number;
    insuranceCode?: string | null;
    insuranceDescription?: string | null;
    physicianIncluded?: boolean | null;
    isContracted?: boolean | null;
    codeAndDescription: string;
}

export interface LinkExternalLoginRequest {
    email: string;
    provider: string;
    providerKey: string;
    providerDisplayName?: string | null;
}

export interface LinkExternalLoginResult {
    succeeded: boolean;
    errors?: string[] | null;
}

export interface PatientDto {
    id: number;
    mrn: string;
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: string | null;
    gender?: Gender;
}

export interface ProblemDetails {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;

    [key: string]: any;
}

export enum ProviderType {
    _0 = 0,
    _1 = 1,
}

export interface ServiceTypeDto {
    id: number;
    description?: string | null;
    cptCode?: number | null;
}

export interface UpdateEmployeeRequest {
    firstName: string;
    lastName: string;
    titleExtension?: string | null;
    role: ProviderType;
    canApproveVisits: boolean;
}

export interface UpdateFacilityRequest {
    facilityName?: string | null;
    facilityAbbreviation?: string | null;
}

export interface UpdateInsuranceRequest {
    insuranceCode?: string | null;
    insuranceDescription?: string | null;
    physicianIncluded?: boolean | null;
    isContracted?: boolean | null;
    codeAndDescription: string;
}

export interface UpdateServiceTypeRequest {
    description?: string | null;
    cptCode?: number | null;
}

export interface UpdateVisitRequest {
    serviceTypeId: number;
    isScribeServiceOnly: boolean;
    physicianApproved: boolean;
    nursePractitionerApproved: boolean;
    physicianApprovedDateTime: string;
    physicianApprovedBy?: string | null;
}

export interface VisitDto {
    id: number;
}

export interface VisitEventDto {
    description: string;
    enteredByUserId: number;
    eventOccurredAt: string;
    eventTypeId: number;
    id: number;
    visitId: number;
}

export interface VisitEventTypeDto {
    id: number;
    code: string;
    name: string;
    iconName?: string | null;
    color?: string | null;
}

export interface FileParameter {
    data: any;
    fileName: string;
}

}