//----------------------
// <auto-generated>
//     Generated using NSwag toolchain (http://NSwag.org)
//     Post-processed to organize into module namespaces based on OpenAPI tags
//
//     This file was automatically generated. Do not modify manually.
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming


export namespace Assignments {

  export interface Microsoft_AspNetCore_Mvc_ProblemDetails {
      type?: string | null;
      title?: string | null;
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
      [key: string]: any;
  }

}


export namespace Auth {

  export interface AuthenticateUserRequest {
      userName: string;
      password: string;
  }

  export interface ClaimDto {
      type: string;
      value: string;
  }

  export interface Consilient_Api_Controllers_AuthenticateUserApiResponse {
      succeeded: boolean;
      errors?: string[] | null;
      userClaims?: ClaimDto[] | null;
  }

  export interface ExternalAuthenticateRequest {
      provider: string;
      code: string;
      codeVerifier: string;
      redirectUri: string;
  }

  export interface LinkExternalLoginRequest {
      email: string;
      provider: string;
      providerKey: string;
      providerDisplayName?: string | null;
  }

  export interface LinkExternalLoginResult {
      succeeded: boolean;
      errors?: string[] | null;
  }

}


export namespace Common {

  export interface FileParameter {
      data: any;
      fileName: string;
  }

}


export namespace Employees {

  export interface CreateEmployeeRequest {
      firstName?: string | null;
      lastName?: string | null;
      titleExtension?: string | null;
      isProvider: boolean;
      role?: string | null;
      isAdministrator: boolean;
      email?: string | null;
      canApproveVisits: boolean;
  }

  export interface EmployeeDto {
      id: number;
      firstName?: string | null;
      lastName?: string | null;
      titleExtension?: string | null;
      isProvider: boolean;
      role?: string | null;
      isAdministrator: boolean;
      email?: string | null;
      canApproveVisits: boolean;
  }

  export interface EmployeeVisitCountDto {
      employeeId: number;
      employeeLastName: string;
      employeeFirstName: string;
      role: string;
      facilityId: number;
      facilityAbbreviation: string;
      patientId: number;
      patientMRN: number;
      patientLastName: string;
      patientFirstName: string;
      visitId: number;
      dateServiced: string;
      room: string;
      bed: string;
  }

  export interface UpdateEmployeeRequest {
      firstName?: string | null;
      lastName?: string | null;
      titleExtension?: string | null;
      isProvider: boolean;
      role?: string | null;
      isAdministrator: boolean;
      canApproveVisits: boolean;
  }

}


export namespace Facilities {

  export interface CreateFacilityRequest {
      facilityName?: string | null;
      facilityAbbreviation?: string | null;
  }

  export interface FacilityDto {
      id: number;
      name?: string | null;
      abbreviation?: string | null;
  }

  export interface UpdateFacilityRequest {
      facilityName?: string | null;
      facilityAbbreviation?: string | null;
  }

}


export namespace GraphQl {

  export interface Consilient_Data_GraphQL_GraphQlError {
      message: string;
  }

  export interface Consilient_Data_GraphQL_QueryRequest {
      query?: string | null;
  }

  export interface Consilient_Data_GraphQL_QueryResult {
      errors?: Consilient_Data_GraphQL_GraphQlError[] | null;
      data?: { [key: string]: any; } | null;
      extensions?: { [key: string]: any; } | null;
  }

}


export namespace Hospitalizations {

  export interface HospitalizationDto {
      id: number;
      patientId: number;
      caseId: number;
      facilityId: number;
      psychEvaluation: boolean;
      admissionDate: string;
      dischargeDate?: string | null;
      hospitalizationStatusId: number;
  }

  export interface HospitalizationStatusDto {
      id: number;
      code: string;
      name: string;
      billingCode: string;
      color: string;
      displayOrder: number;
      type: HospitalizationStatusDtoType;
      iconName?: string | null;
  }

  export enum HospitalizationStatusDtoType {
      _0 = 0,
      _1 = 1,
  }

}


export namespace Insurances {

  export interface CreateInsuranceRequest {
      insuranceCode?: string | null;
      insuranceDescription?: string | null;
      physicianIncluded?: boolean | null;
      isContracted?: boolean | null;
      codeAndDescription: string;
  }

  export interface InsuranceDto {
      id: number;
      insuranceCode?: string | null;
      insuranceDescription?: string | null;
      physicianIncluded?: boolean | null;
      isContracted?: boolean | null;
      codeAndDescription: string;
  }

  export interface UpdateInsuranceRequest {
      insuranceCode?: string | null;
      insuranceDescription?: string | null;
      physicianIncluded?: boolean | null;
      isContracted?: boolean | null;
      codeAndDescription: string;
  }

}


export namespace Patients {

  export interface CreatePatientRequest {
      mrn: number;
      firstName?: string | null;
      lastName?: string | null;
      patientBirthDate?: string | null;
  }

  export interface PatientDto {
      id: number;
      mrn: string;
      firstName?: string | null;
      lastName?: string | null;
      dateOfBirth?: string | null;
      gender?: PatientDtoGender | null;
  }

  export enum PatientDtoGender {
      _1 = 1,
      _2 = 2,
      _3 = 3,
  }

}


export namespace ServiceTypes {

  export interface CreateServiceTypeRequest {
      description?: string | null;
      cptCode?: number | null;
  }

  export interface ServiceTypeDto {
      id: number;
      description?: string | null;
      cptCode?: number | null;
  }

  export interface UpdateServiceTypeRequest {
      description?: string | null;
      cptCode?: number | null;
  }

}


export namespace VisitEvents {

  export interface InsertVisitEventRequest {
      visitId: number;
      eventTypeId: number;
      eventOccurredAt: string;
      description: string;
  }

  export interface VisitEventDto {
      description: string;
      enteredByUserId: number;
      eventOccurredAt: string;
      eventTypeId: number;
      id: number;
      visitId: number;
  }

  export interface VisitEventTypeDto {
      id: number;
      code: string;
      name: string;
      iconName?: string | null;
      color?: string | null;
  }

}


export namespace Visits {

  export interface CreateVisitRequest {
      dateServiced: string;
      hospitalizationId: number;
      serviceTypeId: number;
      isScribeServiceOnly: boolean;
  }

  export interface UpdateVisitRequest {
      serviceTypeId: number;
      isScribeServiceOnly: boolean;
      physicianApproved: boolean;
      nursePractitionerApproved: boolean;
      physicianApprovedDateTime: string;
      physicianApprovedBy?: string | null;
  }

  export interface VisitDto {
      id: number;
  }

}
