// <auto-generated />
using System;
using Consilient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Migrations
{
    [DbContext(typeof(ConsilientDbContext))]
    [Migration("20251111023227_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consilient.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanApproveVisits")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProvider")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TitleExtension")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees", "Compensation");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityAbbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FacilityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Facilities", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Hospitalization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DischargeDate")
                        .HasColumnType("date");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Hospitalization");

                    b.HasAlternateKey("CaseId")
                        .HasName("AK_Hospitalizations_CaseId");

                    b.HasAlternateKey("CaseId", "PatientId")
                        .HasName("AK_Hospitalizations_CaseId_PatientId");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("IX_Hospitalizations_FacilityId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Hospitalizations_PatientId");

                    b.ToTable("Hospitalizations", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InsuranceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeAndDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsuranceCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InsuranceDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsContracted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("PhysicianIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Insurances", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("PatientBirthDate")
                        .HasColumnType("date");

                    b.Property<string>("PatientFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientLastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PatientMrn")
                        .HasColumnType("int")
                        .HasColumnName("PatientMRN");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasAlternateKey("PatientMrn")
                        .HasName("AK_Patients_PatientMrn");

                    b.ToTable("Patients", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.PatientVisitStaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientVisit_StagingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AddedToMainTable")
                        .HasColumnType("bit");

                    b.Property<int?>("AdmissionNumber")
                        .HasColumnType("int");

                    b.Property<int?>("CosigningPhysicianEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("CosigningPhysicianEmployeeID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateServiced")
                        .HasColumnType("date");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int")
                        .HasColumnName("InsuranceID");

                    b.Property<bool>("IsScribeServiceOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("NursePractitionerApproved")
                        .HasColumnType("bit");

                    b.Property<int?>("NursePractitionerEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("NursePractitionerEmployeeID");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<bool>("PhysicianApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PhysicianApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PhysicianApprovedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PhysicianEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("PhysicianEmployeeID");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ScribeEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ScribeEmployeeID");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceTypeID");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CosigningPhysicianEmployeeId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("InsuranceId");

                    b.HasIndex("NursePractitionerEmployeeId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhysicianEmployeeId");

                    b.HasIndex("ScribeEmployeeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("PatientVisits_Staging", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeAndDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cptcode")
                        .HasColumnType("int")
                        .HasColumnName("CPTCode");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientVisitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CosigningPhysicianEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("CosigningPhysicianEmployeeID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateServiced")
                        .HasColumnType("date");

                    b.Property<int>("HospitalizationId")
                        .HasColumnType("int")
                        .HasColumnName("HospitalizationID");

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int")
                        .HasColumnName("InsuranceID");

                    b.Property<bool>("IsScribeServiceOnly")
                        .HasColumnType("bit");

                    b.Property<int>("IsSupervising")
                        .HasColumnType("int");

                    b.Property<int?>("NursePractitionerEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("NursePractitionerEmployeeID");

                    b.Property<int>("PhysicianEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("PhysicianEmployeeID");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ScribeEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("ScribeEmployeeID");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceTypeID");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CosigningPhysicianEmployeeId");

                    b.HasIndex("HospitalizationId");

                    b.HasIndex("InsuranceId");

                    b.HasIndex("NursePractitionerEmployeeId");

                    b.HasIndex("PhysicianEmployeeId");

                    b.HasIndex("ScribeEmployeeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("PatientVisits", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.VwPatientVisit", b =>
                {
                    b.Property<DateOnly>("DateServiced")
                        .HasColumnType("date");

                    b.Property<string>("FacilityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Insurance")
                        .HasMaxLength(113)
                        .HasColumnType("nvarchar(113)");

                    b.Property<string>("NursePractitioner")
                        .HasMaxLength(105)
                        .HasColumnType("nvarchar(105)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)");

                    b.Property<int>("PatientVisitId")
                        .HasColumnType("int")
                        .HasColumnName("PatientVisitID");

                    b.Property<string>("Physician")
                        .HasMaxLength(105)
                        .HasColumnType("nvarchar(105)");

                    b.Property<string>("Scribe")
                        .HasMaxLength(105)
                        .HasColumnType("nvarchar(105)");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(133)
                        .HasColumnType("nvarchar(133)");

                    b.ToTable((string)null);

                    b.ToView("vw_PatientVisits", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.VwPatientVisitsCompareToLive", b =>
                {
                    b.Property<string>("AttendingPhysicianJoinId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AttendingPhysicianJoinID");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int")
                        .HasColumnName("CaseID");

                    b.Property<string>("CosignPhysicianJoinId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CosignPhysicianJoinID");

                    b.Property<int?>("Cptcd")
                        .HasColumnType("int")
                        .HasColumnName("CPTCD");

                    b.Property<int?>("ImportFileNm")
                        .HasColumnType("int")
                        .HasColumnName("ImportFileNM");

                    b.Property<string>("InsuranceNm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("InsuranceNM");

                    b.Property<int?>("ModifiedDts")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedDTS");

                    b.Property<int?>("Mrn")
                        .HasColumnType("int")
                        .HasColumnName("MRN");

                    b.Property<string>("NursePractitionerJoinId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NursePractitionerJoinID");

                    b.Property<DateOnly?>("PatientBirthDts")
                        .HasColumnType("date")
                        .HasColumnName("PatientBirthDTS");

                    b.Property<string>("PatientNm")
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)")
                        .HasColumnName("PatientNM");

                    b.Property<string>("ScribeNm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ScribeNM");

                    b.Property<DateOnly>("ServiceDts")
                        .HasColumnType("date")
                        .HasColumnName("ServiceDTS");

                    b.ToTable((string)null);

                    b.ToView("vw_PatientVisits_CompareToLive", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.VwPatientVisitsStaging", b =>
                {
                    b.Property<DateOnly>("DateServiced")
                        .HasColumnType("date");

                    b.Property<string>("FacilityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Insurance")
                        .HasMaxLength(113)
                        .HasColumnType("nvarchar(113)");

                    b.Property<string>("NursePractitioner")
                        .HasMaxLength(105)
                        .HasColumnType("nvarchar(105)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)");

                    b.Property<int>("PatientVisitStagingId")
                        .HasColumnType("int")
                        .HasColumnName("PatientVisit_StagingID");

                    b.Property<string>("Physician")
                        .HasMaxLength(105)
                        .HasColumnType("nvarchar(105)");

                    b.Property<string>("Scribe")
                        .HasMaxLength(105)
                        .HasColumnType("nvarchar(105)");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(133)
                        .HasColumnType("nvarchar(133)");

                    b.ToTable((string)null);

                    b.ToView("vw_PatientVisits_Staging", "Clinical");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Hospitalization", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Hospitalizations_Facilities_FacilityId");

                    b.HasOne("Consilient.Data.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Hospitalizations_Patients_PatientId");

                    b.Navigation("Facility");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Consilient.Data.Entities.PatientVisitStaging", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Employee", "CosigningPhysicianEmployee")
                        .WithMany()
                        .HasForeignKey("CosigningPhysicianEmployeeId")
                        .HasConstraintName("FK_PatientVisits_Staging_CosignPhysicianEmployee");

                    b.HasOne("Consilient.Data.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientVisits_Staging_Facility");

                    b.HasOne("Consilient.Data.Entities.Insurance", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .HasConstraintName("FK_PatientVisits_Staging_Insurance");

                    b.HasOne("Consilient.Data.Entities.Employee", "NursePractitionerEmployee")
                        .WithMany()
                        .HasForeignKey("NursePractitionerEmployeeId")
                        .HasConstraintName("FK_PatientVisits_Staging_NursePractitioner");

                    b.HasOne("Consilient.Data.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientVisits_Staging_Patient");

                    b.HasOne("Consilient.Data.Entities.Employee", "PhysicianEmployee")
                        .WithMany()
                        .HasForeignKey("PhysicianEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientVisits_Staging_Physician");

                    b.HasOne("Consilient.Data.Entities.Employee", "ScribeEmployee")
                        .WithMany()
                        .HasForeignKey("ScribeEmployeeId")
                        .HasConstraintName("FK_PatientVisits_Staging_Scribe");

                    b.HasOne("Consilient.Data.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .HasConstraintName("FK_PatientVisits_Staging_ServiceType");

                    b.Navigation("CosigningPhysicianEmployee");

                    b.Navigation("Facility");

                    b.Navigation("Insurance");

                    b.Navigation("NursePractitionerEmployee");

                    b.Navigation("Patient");

                    b.Navigation("PhysicianEmployee");

                    b.Navigation("ScribeEmployee");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Consilient.Data.Entities.Visit", b =>
                {
                    b.HasOne("Consilient.Data.Entities.Employee", "CosigningPhysicianEmployee")
                        .WithMany()
                        .HasForeignKey("CosigningPhysicianEmployeeId")
                        .HasConstraintName("FK_PatientVisits_CosignPhysicianEmployee");

                    b.HasOne("Consilient.Data.Entities.Hospitalization", "Hospitalization")
                        .WithMany()
                        .HasForeignKey("HospitalizationId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientVisits_Hospitalizations");

                    b.HasOne("Consilient.Data.Entities.Insurance", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceId")
                        .HasConstraintName("FK_PatientVisits_Insurances");

                    b.HasOne("Consilient.Data.Entities.Employee", "NursePractitionerEmployee")
                        .WithMany()
                        .HasForeignKey("NursePractitionerEmployeeId")
                        .HasConstraintName("FK_PatientVisits_NursePractitioner");

                    b.HasOne("Consilient.Data.Entities.Employee", "PhysicianEmployee")
                        .WithMany()
                        .HasForeignKey("PhysicianEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientVisits_Physician");

                    b.HasOne("Consilient.Data.Entities.Employee", "ScribeEmployee")
                        .WithMany()
                        .HasForeignKey("ScribeEmployeeId")
                        .HasConstraintName("FK_PatientVisits_Scribe");

                    b.HasOne("Consilient.Data.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientVisits_ServiceType");

                    b.Navigation("CosigningPhysicianEmployee");

                    b.Navigation("Hospitalization");

                    b.Navigation("Insurance");

                    b.Navigation("NursePractitionerEmployee");

                    b.Navigation("PhysicianEmployee");

                    b.Navigation("ScribeEmployee");

                    b.Navigation("ServiceType");
                });
#pragma warning restore 612, 618
        }
    }
}
